[package]
name = "fuber"
version = "0.1.0"
edition = "2021"

[lib]
name = "fuber"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.140"
serde_json = "1.0.85"

[[bin]]
name = "fuber"
path = "src/main.rs"
